services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - quiz_portal_network
    container_name: quiz_portal_web
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - NODE_ENV=production
    env_file:
      - ./.env

  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy_certs:/etc/nginx/certs:ro
      - proxy_vhost:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html
      - acme_sh:/etc/acme.sh
    restart: always
    networks:
      - quiz_portal_network

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: letsencrypt-companion
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy_certs:/etc/nginx/certs:rw
      - proxy_vhost:/etc/nginx/vhost.d
      - proxy_html:/usr/share/nginx/html
      - acme_sh:/etc/acme.sh
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - quiz_portal_network

volumes:
  proxy_certs:
  proxy_vhost:
  proxy_html:
  acme_sh:


networks:
  quiz_portal_network:
    driver: bridge
